name: Docker Image Downloader
on: workflow_dispatch
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Image
        run: docker pull quay.io/ascend/vllm-ascend:v0.13.0rc1
      
      - name: Save Image to Tar
        run: docker save quay.io/ascend/vllm-ascend:v0.13.0rc1 -o vllm-ascend.tar
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vllm-ascend-image
          path: vllm-ascend.tar
          retention-days: 1
